# Generated by Django 5.0.2 on 2024-02-27 07:33

import app_instagram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('path', models.ImageField(upload_to=app_instagram.models.update_filename)),
            ],
        ),
    ]
